version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: astrokabinet_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount storage & bootstrap/cache untuk persistensi
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
      # Mount .env production
      - ./.env.production:/app/.env
      # Mount logs
      - ./storage/logs:/var/log/supervisor
    networks:
      - astrokabinet
    # Koneksi ke MySQL di host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  astrokabinet:
    driver: bridge
