version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: astrokabinet_app
        restart: unless-stopped
        volumes:
            # Mount storage & bootstrap/cache untuk persistensi
            - ./storage:/app/storage
            - ./bootstrap/cache:/app/bootstrap/cache
            # Mount .env production
            - ./.env.production:/app/.env
        networks:
            - astrokabinet
        # Koneksi ke MySQL dan Redis di host
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "9000:9000"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false

    nginx:
        image: nginx:alpine
        container_name: astrokabinet_nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public:/var/www/astrokabinet.id/public:ro
            - ./storage/app/public:/var/www/astrokabinet.id/storage/app/public:ro
            - ./deployment/nginx/docker-nginx.conf:/etc/nginx/conf.d/default.conf:ro
            # SSL certificates (akan dibuat nanti)
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - app
        networks:
            - astrokabinet

networks:
    astrokabinet:
        driver: bridge
