version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            # Mount storage & bootstrap/cache untuk persistensi
            - ./storage:/app/storage
            - ./bootstrap/cache:/app/bootstrap/cache
        networks:
            - laravel

        # Ini adalah bagian kunci untuk menghubungkan kontainer ke MySQL di HOST
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    laravel:
        driver: bridge
