version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.frankenphp
    container_name: astrokabinet_frankenphp
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount storage & bootstrap/cache untuk persistensi
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
      # Mount .env production
      - ./.env.production:/app/.env
    networks:
      - astrokabinet
    # Koneksi ke MySQL di host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - SERVER_NAME=:80

networks:
  astrokabinet:
    driver: bridge
